# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      MAINNET_URL: ${{ secrets.MAINNET_RPC_URL }}
      FOUNDRY_PROFILE: "test"
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.11.0

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: pnpm i
      - run: pnpm lint:check
      - run: forge build
      - run: forge test
